variables:
  INCLUDE_CICD_REF_BRANCH:
    value: "main"
    description: "Welcher Branch soll f√ºr die Pipeline genutzt werden?"
  MAVEN_IMAGE: "$MAVEN_IMAGE_38_JDK17"

include:
  - project: "$INCLUDE_CICD_PROJECT"
    ref: "$INCLUDE_CICD_REF_BRANCH"
    file:
      - "$INCLUDE_CICD_GITLAB_YML"
